# Generated by Django 4.1.7 on 2023-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('5', '5 Stars'), ('4.5', '4.5 Stars'), ('4', '4 Stars'), ('3.5', '3.5 Stars'), ('3', '3 Stars'), ('2.5', '2.5 Stars'), ('2', '2 Stars'), ('1.5', '1.5 Stars'), ('1', '1 Star'), ('0.5', 'Half a Star'), ('0', 'Zero Stars')], default='2.5', max_length=5),
        ),
    ]
